### ISSUE TITLE
Use `PropertyResourceBundle` to support UTF-8 on Java 9+

### ISSUE THREAD

**Issue by timja** [jenkinsci/stapler#356]
### What feature do you want to see added?

It's been a long standing issue that Jenkins properties files are not UTF-8, many issues have been caused for this and it has a poor developer experience currently.

From @basil
> [jenkinsci/stapler@2905144/jelly/src/main/java/org/kohsuke/stapler/jelly/ResourceBundle.java#L155-L165=](https://github.com/jenkinsci/stapler/blob/2905144023e5728743ffc2357f506bbc0039f9ee/jelly/src/main/java/org/kohsuke/stapler/jelly/ResourceBundle.java#L155-L165=) could be converted to use PropertyResourceBundle, which (as of Java 9+, which we will begin requiring in September) [first loads property files in UTF-8, falling back to ISO-8859-1 otherwise](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/PropertyResourceBundle.html).

see https://github.com/jenkinsci/design-library-plugin/pull/41#discussion_r864164760

**Comment by basil** [comment]
I have no plans to work on this. Pull requests are welcome.
