### ISSUE TITLE
stapler:bind is creating inline javascript

### ISSUE THREAD

**Issue by mawinter69** [jenkinsci/stapler#457]
### What feature do you want to see added?

using `<st:bind var="myproxy" value="${it}"/>`result in the following code getting injected in the rendered page:
```
<script>
myproxy = makeStaplerProxy(...)
</script>
```
This is a problem when Content Security Policy should be enabled.
Maybe  one can just create some json data
```
<script class="stapler-javascript-proxy" type="application/json">
  {"myproxy": {"url": "/jenkins/$stapler/bound/dcabcdd4-f80d-4b46-b5f7-db0ce94ab8ff",
               "crumb": "abc234d97ed766f5...",
               "methods": ["myfirstmethod", "mysecondmethod"] 
               }
  }
</script>
```
The bind.js could then find the data and do the assignment to the variable.

**Comment by timja** [comment]
There's a PR here for this https://github.com/jenkinsci/stapler/pull/385 from @daniel-beck

**Comment by MarkEWaite** [comment]
Merged and included in [Stapler release 1839.ved17667b_a_eb_5](https://github.com/jenkinsci/stapler/releases/tag/1839.ved17667b_a_eb_5)

**Comment by daniel-beck** [comment]
Depends on https://github.com/jenkinsci/jenkins/pull/6865 to work though. Reviews still welcome!
