### ISSUE TITLE
Replace obsolete `application/javascript` content type with `text/javascript`

### ISSUE THREAD

**Issue by MarkEWaite** [jenkinsci/stapler#515]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```
Jenkins 2.426.3 and newer
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

All operating systems

### Reproduction steps

1. When running tests with HTMLUnit 3.11.0 or newer. many warnings are reported for the use of the obsolete `application/javascript` content type.  The [IANA page](https://www.iana.org/assignments/media-types/application/javascript) and [RFC 9239](https://datatracker.ietf.org/doc/rfc9239/) both declare that `application/javascript` is an obsolete form of `text/javascript`

### Expected Results

1. Warnings are no longer displayed by most HTMLUnit tests in Jenkins core and plugins once a new version of Stapler is released with the JavaScript content type changed to `text/javascript`
2. Automated tests in Jenkins core continue to pass with that new version of Stapler (at least one test will need to be updated for the new Stapler release)
3. Automated tests in most plugins no longer display the warning when tested with a Jenkins core version that includes the new release of Stapler

### Actual Results

Warning messages are displayed by HTMLUnit 3.11.0 like:

```
WARNING o.h.IncorrectnessListenerImpl#notify: Obsolete content type encountered: 'application/javascript' for remotely loaded JavaScript element at 'http://localhost:45275/jenkins/adjuncts/...'.
```

### Anything else?

Discovered while evaluating HTMLUnit 3.11.0 as part of

* https://github.com/jenkinsci/jenkins-test-harness-htmlunit/pull/140

### Are you interested in contributing a fix?

Possibly, but not for a month or two at least

**Comment by basil** [comment]
Fixed in #521.
