### ISSUE TITLE
Stapler-jruby: Not all riutable methods are being returned by RubyKlassNavigator#getFunctions()

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/stapler#87]
In stapler-1.246 there was a new `KlassNavigator#getFunctions()` introduced. During implementations of the tests for JENKINS-39414 I have discovered the implementation in `RubyKlassNavigator` does not actually return all routable methods.

**Comment by basil** [comment]
JRuby support was removed in #308.
